dist: trusty
language: node_js

node_js:
  - '10'

addons:
  sonarcloud:
    organization: 'helenfranca-github'
    token:
      secure: 4c9ab85eae889eca3925b9bbca17364d1bba7977

services:
  - postgresql

branches:
  only:
    # - master
    - features

before_install:
  - npm i -g npm@6.4.1

install:
  - npm install

script:
  # - npm run test
  - sonar-scanner
# deploy:
#   provider: heroku
#   api_key:
#   app: doacaodesangue
